import type { Database } from "@/types/database.types";
import type { ProductWithDetails } from "@/actions/product.actions";

export const MOCK_CATEGORIES: Database["public"]["Tables"]["categories"]["Row"][] = [
  {
    id: "cat-dimsum",
    name: "Dimsum",
    type: "food",
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-minuman",
    name: "Minuman",
    type: "drink",
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: ProductWithDetails[] = [
  {
    id: "prod-dimsum-mentai-lava",
    name: "Dimsum Mentai Cheese Lava",
    sku: "DIM-MEN-01",
    description: "Dimsum kukus gurih dibalut saus mentai bakar dan lelehan keju mozzarella.",
    category_id: "cat-dimsum",
    base_price: 24000,
    cost_price: 13000,
    stock_qty: 45,
    low_stock_threshold: 10,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-dm-reg",
        product_id: "prod-dimsum-mentai-lava",
        name: "Regular (4 pcs)",
        price: 24000,
        cost_price: 13000,
        sku: "DIM-MEN-01-REG",
        is_default: true,
        is_active: true,
        sort_order: 1,
      },
      {
        id: "var-dm-jumbo",
        product_id: "prod-dimsum-mentai-lava",
        name: "Jumbo Box (8 pcs)",
        price: 44000,
        cost_price: 24000,
        sku: "DIM-MEN-01-JMB",
        is_default: false,
        is_active: true,
        sort_order: 2,
      },
    ],
    product_modifier_groups: [
      {
        group: {
          id: "modgrp-pedas",
          name: "Level Pedas",
          selection: "single",
          is_required: true,
          min_select: 1,
          max_select: 1,
          sort_order: 1,
          is_active: true,
          modifiers: [
            {
              id: "mod-pedas-normal",
              group_id: "modgrp-pedas",
              name: "Level 1 (Normal)",
              price_delta: 0,
              cost_delta: 0,
              sort_order: 1,
              is_active: true,
            },
            {
              id: "mod-pedas-sedang",
              group_id: "modgrp-pedas",
              name: "Level 2 (Pedas Mantap)",
              price_delta: 0,
              cost_delta: 0,
              sort_order: 2,
              is_active: true,
            },
            {
              id: "mod-pedas-ekstra",
              group_id: "modgrp-pedas",
              name: "Level 3 (Ekstra Pedas)",
              price_delta: 2000,
              cost_delta: 500,
              sort_order: 3,
              is_active: true,
            },
          ],
        },
      },
      {
        group: {
          id: "modgrp-extra-cheese",
          name: "Topping Tambahan",
          selection: "multiple",
          is_required: false,
          min_select: 0,
          max_select: 3,
          sort_order: 2,
          is_active: true,
          modifiers: [
            {
              id: "mod-extra-mozza",
              group_id: "modgrp-extra-cheese",
              name: "Ekstra Keju Mozzarella Melt",
              price_delta: 5000,
              cost_delta: 2500,
              sort_order: 1,
              is_active: true,
            },
            {
              id: "mod-nori-flakes",
              group_id: "modgrp-extra-cheese",
              name: "Taburan Nori Panggang",
              price_delta: 2000,
              cost_delta: 500,
              sort_order: 2,
              is_active: true,
            },
          ],
        },
      },
    ],
  },
  {
    id: "prod-dimsum-kukus-udang",
    name: "Dimsum Kukus Ayam Udang",
    sku: "DIM-KUK-01",
    description: "Dimsum lembut kukus hangat khas dengan chili oil segar.",
    category_id: "cat-dimsum",
    base_price: 18000,
    cost_price: 9000,
    stock_qty: 60,
    low_stock_threshold: 10,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-dku-4",
        product_id: "prod-dimsum-kukus-udang",
        name: "Porsi 4 pcs",
        price: 18000,
        cost_price: 9000,
        sku: "DIM-KUK-01-4",
        is_default: true,
        is_active: true,
        sort_order: 1,
      },
      {
        id: "var-dku-6",
        product_id: "prod-dimsum-kukus-udang",
        name: "Porsi 6 pcs",
        price: 26000,
        cost_price: 13000,
        sku: "DIM-KUK-01-6",
        is_default: false,
        is_active: true,
        sort_order: 2,
      },
    ],
    product_modifier_groups: [],
  },
  {
    id: "prod-dimsum-goreng-mozza",
    name: "Dimsum Goreng Mozzarella Melt",
    sku: "DIM-GOR-01",
    description: "Dimsum goreng krispi renyah dengan keju lumer di dalamnya.",
    category_id: "cat-dimsum",
    base_price: 20000,
    cost_price: 10000,
    stock_qty: 35,
    low_stock_threshold: 5,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: false,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [],
    product_modifier_groups: [],
  },
  {
    id: "prod-mango-cheese-tea",
    name: "Mango Cream Cheese Drink",
    sku: "DRK-MNG-01",
    description: "Minuman mangga manis segar dipadu cream cheese gurih lembut.",
    category_id: "cat-minuman",
    base_price: 18000,
    cost_price: 8000,
    stock_qty: 75,
    low_stock_threshold: 15,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    variants: [
      {
        id: "var-mng-med",
        product_id: "prod-mango-cheese-tea",
        name: "Medium Cup",
        price: 18000,
        cost_price: 8000,
        sku: "DRK-MNG-01-M",
        is_default: true,
        is_active: true,
        sort_order: 1,
      },
      {
        id: "var-mng-lrg",
        product_id: "prod-mango-cheese-tea",
        name: "Large Cup (16oz)",
        price: 22000,
        cost_price: 10000,
        sku: "DRK-MNG-01-L",
        is_default: false,
        is_active: true,
        sort_order: 2,
      },
    ],
    product_modifier_groups: [
      {
        group: {
          id: "modgrp-sugar",
          name: "Tingkat Manis",
          selection: "single",
          is_required: true,
          min_select: 1,
          max_select: 1,
          sort_order: 1,
          is_active: true,
          modifiers: [
            {
              id: "mod-sugar-100",
              group_id: "modgrp-sugar",
              name: "Normal Sweet (100%)",
              price_delta: 0,
              cost_delta: 0,
              sort_order: 1,
              is_active: true,
            },
            {
              id: "mod-sugar-70",
              group_id: "modgrp-sugar",
              name: "Less Sweet (70%)",
              price_delta: 0,
              cost_delta: 0,
              sort_order: 2,
              is_active: true,
            },
          ],
        },
      },
      {
        group: {
          id: "modgrp-drink-toppings",
          name: "Pilihan Topping",
          selection: "multiple",
          is_required: false,
          min_select: 0,
          max_select: 3,
          sort_order: 2,
          is_active: true,
          modifiers: [
            {
              id: "mod-top-boba",
              group_id: "modgrp-drink-toppings",
              name: "Boba Pearl Kenyal",
              price_delta: 3000,
              cost_delta: 1000,
              sort_order: 1,
              is_active: true,
            },
            {
              id: "mod-top-cream-cheese",
              group_id: "modgrp-drink-toppings",
              name: "Ekstra Cheese Foam",
              price_delta: 5000,
              cost_delta: 2000,
              sort_order: 2,
              is_active: true,
            },
          ],
        },
      },
    ],
  },
  {
    id: "prod-matcha-cheese-tea",
    name: "Matcha Cheese Macchiato",
    sku: "DRK-MTC-01",
    description: "Teh matcha Jepang autentik dengan foam keju tebal gurih.",
    category_id: "cat-minuman",
    base_price: 19000,
    cost_price: 8500,
    stock_qty: 50,
    low_stock_threshold: 10,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: false,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    variants: [],
    product_modifier_groups: [],
  },
  {
    id: "prod-brown-sugar-cheese",
    name: "Brown Sugar Boba Cheese",
    sku: "DRK-BSB-01",
    description: "Gula aren karamel legit dengan boba kenyal dan krim keju.",
    category_id: "cat-minuman",
    base_price: 22000,
    cost_price: 9500,
    stock_qty: 40,
    low_stock_threshold: 10,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1558857563-b37fcda70a59?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    variants: [],
    product_modifier_groups: [],
  },
  {
    id: "prod-jasmine-cheese-tea",
    name: "Jasmine Green Tea Cheese",
    sku: "DRK-JSM-01",
    description: "Teh melati wangi menyegarkan berpadu foam keju creamy.",
    category_id: "cat-minuman",
    base_price: 15000,
    cost_price: 6000,
    stock_qty: 60,
    low_stock_threshold: 10,
    track_stock: true,
    image_url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    is_available: true,
    is_active: true,
    is_favorite: false,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    variants: [],
    product_modifier_groups: [],
  },
];

export const MOCK_DISCOUNTS: Database["public"]["Tables"]["discounts"]["Row"][] = [
  {
    id: "disc-pelanggan-baru",
    name: "Diskon Pelanggan Baru 10%",
    code: "NEW10",
    type: "percent",
    value: 10,
    min_purchase: 20000,
    max_discount: 15000,
    is_active: true,
    start_at: null,
    end_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "disc-jumat-berkah",
    name: "Potongan Promo Rp 5.000",
    code: "JUMAT5K",
    type: "fixed",
    value: 5000,
    min_purchase: 40000,
    max_discount: null,
    is_active: true,
    start_at: null,
    end_at: null,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_CUSTOMERS: Database["public"]["Tables"]["customers"]["Row"][] = [
  {
    id: "cust-budi",
    name: "Budi Santoso",
    phone: "081234567891",
    notes: "Pelanggan langganan dimsum mentai",
    total_spent: 145000,
    visit_count: 5,
    last_visit_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cust-dewi",
    name: "Dewi Lestari",
    phone: "085678901234",
    notes: "Suka manis 70%",
    total_spent: 86000,
    visit_count: 3,
    last_visit_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_STORE_SETTINGS: Database["public"]["Tables"]["store_settings"]["Row"] = {
  id: 1,
  store_name: "Cheese Drink & Dimsum",
  tagline: "Dimsum Gurih & Aneka Minuman Keju",
  address: "Jl. Melati No. 12, Tebet, Jakarta Selatan",
  phone: "0812-3456-7890",
  logo_url: null,
  instagram: "@cheesedrink.id",
  receipt_header: "🧀 Nikmati Dimsum Gurih & Minuman Keju Segar!",
  receipt_footer: "Terima kasih atas kunjungan Anda! Follow IG: @cheesedrink.id",
  receipt_paper_width: 58,
  show_logo_on_receipt: false,
  tax_enabled: false,
  tax_percent: 0,
  tax_inclusive: true,
  service_enabled: false,
  service_percent: 0,
  rounding_unit: 100,
  order_prefix: "ORD",
  low_stock_default: 10,
  require_owner_pin_for_void: true,
  owner_void_pin_hash: null,
  timezone: "Asia/Jakarta",
  updated_at: new Date().toISOString(),
};

export const MOCK_ACTIVE_SHIFT: Database["public"]["Tables"]["shifts"]["Row"] = {
  id: "shift-demo-001",
  cashier_id: "00000000-0000-0000-0000-000000000002",
  opened_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  closed_at: null,
  opening_cash: 100000,
  expected_cash: 345000,
  actual_cash: null,
  cash_difference: null,
  note: null,
  status: "open",
};

export const MOCK_ORDERS = [
  {
    id: "ord-demo-001",
    order_no: "ORD-20261002-0014",
    queue_no: 14,
    order_type: "take_away" as const,
    channel: "walk_in" as const,
    table_no: null,
    status: "completed" as const,
    subtotal: 42000,
    discount_id: null,
    discount_amount: 0,
    tax_amount: 0,
    service_amount: 0,
    rounding_amount: 0,
    total: 42000,
    paid_amount: 50000,
    change_amount: 8000,
    total_cost: 21000,
    note: null,
    customer_id: null,
    customer_name: "Budi Santoso",
    cashier_id: "00000000-0000-0000-0000-000000000002",
    shift_id: "shift-demo-001",
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    paid_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    voided_at: null,
    voided_by: null,
    void_reason: null,
    updated_at: new Date().toISOString(),
    cashier: { full_name: "Kasir Siti Rahma" },
    payments: [{ id: "pay-1", method: "cash" as const, amount: 50000, reference_no: null }],
    items: [
      { id: "it-1", product_name: "Dimsum Mentai Cheese Lava", variant_name: "Regular (4 pcs)", qty: 1, subtotal: 24000 },
      { id: "it-2", product_name: "Mango Cream Cheese Drink", variant_name: "Medium Cup", qty: 1, subtotal: 18000 },
    ],
  },
  {
    id: "ord-demo-002",
    order_no: "ORD-20261002-0013",
    queue_no: 13,
    order_type: "take_away" as const,
    channel: "walk_in" as const,
    table_no: null,
    status: "completed" as const,
    subtotal: 58000,
    discount_id: "disc-jumat-berkah",
    discount_amount: 5000,
    tax_amount: 0,
    service_amount: 0,
    rounding_amount: 0,
    total: 53000,
    paid_amount: 53000,
    change_amount: 0,
    total_cost: 26000,
    note: null,
    customer_id: null,
    customer_name: "Dewi Lestari",
    cashier_id: "00000000-0000-0000-0000-000000000002",
    shift_id: "shift-demo-001",
    created_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    paid_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    voided_at: null,
    voided_by: null,
    void_reason: null,
    updated_at: new Date().toISOString(),
    cashier: { full_name: "Kasir Siti Rahma" },
    payments: [{ id: "pay-2", method: "qris" as const, amount: 53000, reference_no: "QRIS-89912093" }],
    items: [
      { id: "it-3", product_name: "Dimsum Goreng Mozzarella Melt", variant_name: null, qty: 2, subtotal: 40000 },
      { id: "it-4", product_name: "Matcha Cheese Macchiato", variant_name: null, qty: 1, subtotal: 19000 },
    ],
  },
];
